### ISSUE TITLE
Panic: runtime error: makeslice: len out of range in tiff.(*Tag).convertVals

### ISSUE THREAD

**Issue by parsiya** [xor-gate/goexif2#17]
I ran `go-fuzz` on the project and found two crashes in the same line.

Input is (in hexdump):

```
00000000  49 49 2a 00 08 00 00 00 30 30 30 30 05 00 00 00  |II*.....0000....|
00000010  00 a0 30 30 30 30                                |. 0000|
```

Dump:

```
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/xor-gate/goexif2/tiff.(*Tag).convertVals(0xc04205a280, 0xc042080480, 0xc04200e090)
	/go-fuzz-build214414686/gopath/src/github.com/xor-gate/goexif2/tiff/tag.go:258 +0x88c
github.com/xor-gate/goexif2/tiff.DecodeTag(0x30a0000, 0xc042080480, 0x5605c0, 0x613170, 0x514c20, 0xc04200e06c, 0x0)
	/go-fuzz-build214414686/gopath/src/github.com/xor-gate/goexif2/tiff/tag.go:182 +0x623
github.com/xor-gate/goexif2/tiff.DecodeDir(0x30a0000, 0xc042080480, 0x5605c0, 0x613170, 0xc042080480, 0x0, 0x0, 0x0)
	/go-fuzz-build214414686/gopath/src/github.com/xor-gate/goexif2/tiff/tiff.go:150 +0x1c5
github.com/xor-gate/goexif2/tiff.Decode(0x560240, 0xc042080480, 0x4, 0x4, 0xc042089df0)
	/go-fuzz-build214414686/gopath/src/github.com/xor-gate/goexif2/tiff/tiff.go:99 +0x548
github.com/xor-gate/goexif2/exif.Decode(0x560240, 0xc042080480, 0x5ae92fcc, 0x29751e98, 0x1e9999)
	/go-fuzz-build214414686/gopath/src/github.com/xor-gate/goexif2/exif/exif.go:285 +0x330
github.com/xor-gate/goexif2/exif.Fuzz(0x3900000, 0x16, 0x200000, 0xc042047f48)
	/go-fuzz-build214414686/gopath/src/github.com/xor-gate/goexif2/exif/Fuzz.go:8 +0xba
go-fuzz-dep.Main(0x550580)
	/go-fuzz-build214414686/goroot/src/go-fuzz-dep/main.go:49 +0xb4
main.main()
	/go-fuzz-build214414686/gopath/src/github.com/xor-gate/goexif2/exif/go.fuzz.main/main.go:10 +0x34
exit status 2
```

Panic happens at https://github.com/xor-gate/goexif2/blob/develop/tiff/tag.go#L258:

``` go
case DTRational:
	t.ratVals = make([][]int64, int(t.Count)) // Panic
	for i := range t.ratVals {
		var n, d uint32
```

Looking at value of `t.Count` before that line we see `2684354560`.

`t.Count` is read further up at https://github.com/xor-gate/goexif2/blob/develop/tiff/tag.go#L133:

``` go
err = binary.Read(r, order, &t.Count)
if err != nil {
	return nil, newTiffError("tag component count read failed", err)
}
```

**Solution:** We can check the value of `t.Count` after reading it and discard abnormally large values. I am not familiar enough to the file format to know how large it can be. This can be merged with the check right after L133.

``` go
if t.Count == 1<<32-1 || t.Count > (1<<20-1) {
	return t, newTiffError("invalid Count offset in tag", nil)
}
```

**Comment by xor-gate** [comment]
Thanks @parsiya, I have never run a fuzzy tester on the library. As I am not the original author of the goexif package, I have no idea about the internals of the tiff format. It would indeed be good to let it not panic on valid input. And invalid input should be checked.

**Comment by parsiya** [comment]
I understand, thanks for keeping the project alive. I am currently writing a go-fuzz blog post about this. Will do a pull request about this issue and another crash soon (hopefully).

**Comment by xor-gate** [comment]
Thank you for your effort. We will continue with your PR #18.
